-- 状況確認
SHOW API INTEGRATIONS;
SHOW GIT REPOSITORIES;
SHOW PROCEDURES IN FROSTYFRIDAY_DB.PUBLIC;
SHOW TABLES;

-- 試験用のテーブルを作成して、データを挿入する
CREATE OR REPLACE TRANSIENT TABLE TEST_ADD_ONE (id INT, value INT);
INSERT INTO TEST_ADD_ONE VALUES (1, 10), (2, 20), (3, 30);

-- ストアドプロシージャを呼び出す前、呼び出した結果、呼び出した後をそれぞれ確認
SELECT * FROM TEST_ADD_ONE;
CALL FROSTYFRIDAY_DB.PUBLIC.ADD_ONE_TO_COLUMN('FROSTYFRIDAY_DB.PUBLIC.TEST_ADD_ONE', 'VALUE');
SELECT * FROM TEST_ADD_ONE;

-- gitのリポジトリが更新された場合、FETCHすれば反映される
ALTER GIT REPOSITORY FROSTY_FRIDAY_REPO FETCH;
-- ストアドプロシージャを呼び出す前、呼び出した結果、呼び出した後をそれぞれ確認
SELECT * FROM TEST_ADD_ONE;
CALL FROSTYFRIDAY_DB.PUBLIC.ADD_ONE_TO_COLUMN('FROSTYFRIDAY_DB.PUBLIC.TEST_ADD_ONE', 'VALUE');
SELECT * FROM TEST_ADD_ONE;

-- 以下の設定で作成されたものとする
-- API INTEGRATION：FROSTY_FRIDAY_GIT_API_INTEGRATION
-- GIT REPOSITORIY：FROSTY_FRIDAY_REPO
-- STORED PROCEDURE：ADD_ONE_TO_COLUMN(VARCHAR, VARCHAR)

-- 後片付け
SHOW API INTEGRATIONS;
DROP API INTEGRATION FROSTY_FRIDAY_GIT_API_INTEGRATION;
SHOW GIT REPOSITORIES;
DROP GIT REPOSITORY FROSTY_FRIDAY_REPO;
SHOW PROCEDURES IN FROSTYFRIDAY_DB.PUBLIC;
DROP PROCEDURE ADD_ONE_TO_COLUMN(VARCHAR, VARCHAR);
-- 上の方で作成した試験用のテーブルも削除する
SHOW TABLES;
DROP TABLE TEST_ADD_ONE;