-- GitHubと連携させる
USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE API INTEGRATION github_api_integration
   API_PROVIDER = git_https_api
   API_ALLOWED_PREFIXES = ('https://github.com/')
   API_USER_AUTHENTICATION = (
      TYPE = snowflake_github_app
   )
   ENABLED = TRUE;
USE ROLE POWERUSER;

-- データベースを作成
CREATE OR REPLACE DATABASE FROSTYFRIDAY_DB;

-- 週別にスキーマを作成する
USE DATABASE FROSTYFRIDAY_DB;
CREATE OR REPLACE SCHEMA WEEK140;
CREATE OR REPLACE SCHEMA WEEK149;
CREATE OR REPLACE SCHEMA WEEK150;
